In [142]:
!pip install pandas numpy scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [143]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import TruncatedSVD, LatentDirichletAllocation

import os

In [144]:
df = pd.read_csv("/content/processed_v2.csv")

df = df.rename(columns={"processed_text": "text"})

print("Original size:", df.shape)
df.head()

Original size: (12759, 2)

                                                text label
0  десятки бригад! операція почалась – новий наст...  Fake
1  дуже важкий грип зараз мандрує україною! у діт...  Fake
2  виcтyп гeнceкa нато nідірвaв мережу: “цiнa, як...  Fake
3  залишилися лічені дні, почнеться справжня “м'я...  Fake
4  кремль втретє змінив тактику щодо україни, теп...  Fake

In [145]:
df = df.dropna(subset=["text"])

df["word_len"] = df["text"].apply(lambda x: len(str(x).split()))

df = df[df["word_len"] >= 30]

texts = df["text"].tolist()

print("After filtering:", df.shape)
df.head()

After filtering: (8947, 3)

                                                text label  word_len
0  десятки бригад! операція почалась – новий наст...  Fake       256
1  дуже важкий грип зараз мандрує україною! у діт...  Fake        87
2  виcтyп гeнceкa нато nідірвaв мережу: “цiнa, як...  Fake       149
3  залишилися лічені дні, почнеться справжня “м'я...  Fake       132
4  кремль втретє змінив тактику щодо україни, теп...  Fake       999

In [147]:
stopwords = [
    "і","та","на","що","до","з","за","у","в","не","це","як","для","по", "про","від","але","або","чи","також","його","її","вони","ми",
    "нa", "щo", "тa", "нe", "зa", 'цe', "пpo", "дo", "щօ", 'але', 'по', "він","які","року","під","час","із","після","буде","щоб","aлe",
    "йoгo","тaкoж","пo","вжe","чepeз","вoни","щe","щодо", "можна","був","пам", "про", "дօ", 'чac', 'бyдe', 'тaм', 'тaк', 'дyжe', 'зapaз',
    'хто', 'что','это','єр','the', 'ви', 'бо', 'тут', 'тоді', 'ти', 'нато', 'єс', 'путін'
]

tfidf = TfidfVectorizer(
    max_df=0.05,
    min_df=3,
    stop_words=stopwords
)

count = CountVectorizer(
    max_df=0.05,
    min_df=3,
    stop_words=stopwords
)

X_tfidf = tfidf.fit_transform(texts)
X_count = count.fit_transform(texts)

print("TF-IDF shape:", X_tfidf.shape)
print("Count shape:", X_count.shape)

TF-IDF shape: (8947, 31331)
Count shape: (8947, 31331)

In [148]:
def get_top_words(model, feature_names, n_top=10):
    topics = []
    for topic_idx, topic in enumerate(model.components_):
        top_features = [feature_names[i] for i in topic.argsort()[:-n_top - 1:-1]]
        topics.append(top_features)
    return topics


def print_topics(topics):
    for i, words in enumerate(topics):
        print(f"Topic {i+1}: {', '.join(words)}")

In [149]:
lsa_3 = TruncatedSVD(n_components=3, random_state=42)
lsa_5 = TruncatedSVD(n_components=5, random_state=42)

lsa3_topics = lsa_3.fit_transform(X_tfidf)
lsa5_topics = lsa_5.fit_transform(X_tfidf)

lsa3_words = get_top_words(lsa_3, tfidf.get_feature_names_out())
lsa5_words = get_top_words(lsa_5, tfidf.get_feature_names_out())

print("LSA k=3")
print_topics(lsa3_words)

print("\nLSA k=5")
print_topics(lsa5_words)

LSA k=3
Topic 1: внаслідок, удару, атаки, допомоги, війська, тисяч, кількість, міністр, квітня, військової
Topic 2: внаслідок, удару, ова, атаки, постраждалих, загиблих, обстрілу, загинули, районі, ракетного
Topic 3: напрямку, ппо, військ, знищили, ракет, бпла, ворог, війська, ракети, збили

LSA k=5
Topic 1: внаслідок, удару, атаки, допомоги, війська, тисяч, кількість, міністр, квітня, військової
Topic 2: внаслідок, удару, ова, атаки, постраждалих, загиблих, обстрілу, загинули, районі, ракетного
Topic 3: напрямку, військ, ппо, знищили, бпла, ворог, війська, ракет, населених, донецької
Topic 4: допомоги, євро, млрд, млн, пакет, грн, доларів, військової, ппо, міністр
Topic 5: канали, повідомляють, змі, посиланням, допомоги, пишуть, повідомлення, пакет, telegram, джерела

In [150]:
lda_3 = LatentDirichletAllocation(n_components=3, random_state=42)
lda_5 = LatentDirichletAllocation(n_components=5, random_state=42)

lda3_topics = lda_3.fit_transform(X_count)
lda5_topics = lda_5.fit_transform(X_count)

lda3_words = get_top_words(lda_3, count.get_feature_names_out())
lda5_words = get_top_words(lda_5, count.get_feature_names_out())

print("\nLDA k=3")
print_topics(lda3_words)

print("LDA k=5")
print_topics(lda5_words)

LDA k=3
Topic 1: внаслідок, напрямку, атаки, удару, війська, районі, ударів, росіяни, ворог, окупанти
Topic 2: нас, багато, питання, тільки, міністр, польщі, люди, треба, потрібно, просто
Topic 3: грн, році, млн, дітей, допомоги, євро, гривень, тисяч, суд, президента
LDA k=5
Topic 1: тцк, поліції, служби, мобілізації, сбу, зв, квітня, суд, осіб, поліція
Topic 2: нас, багато, треба, просто, питання, тільки, люди, потрібно, нам, році
Topic 3: допомоги, країн, міністр, році, президента, млн, прем, підтримку, безпеки, євро
Topic 4: укpaїни, канали, 16, аес, повідомляють, навчання, змі, пвк, посиланням, pф
Topic 5: напрямку, внаслідок, атаки, війська, удару, росіяни, військ, окупанти, районі, ударів

In [151]:
def get_top_docs(topic_matrix, texts, top_n=3):
    top_docs = {}

    for topic_idx in range(topic_matrix.shape[1]):
        topic_scores = topic_matrix[:, topic_idx]
        top_indices = topic_scores.argsort()[-top_n:][::-1]

        top_docs[topic_idx] = [texts[i] for i in top_indices]

    return top_docs


lsa5_docs = get_top_docs(lsa5_topics, texts)
lda5_docs = get_top_docs(lda5_topics, texts)

In [152]:
for topic, docs in lsa5_docs.items():
    print(f"\nLSA Topic {topic+1}:")
    for d in docs:
        print("-", d[:200])

for topic, docs in lda5_docs.items():
    print(f"\nLDA Topic {topic+1}:")
    for d in docs:
        print("-", d[:200])

LSA Topic 1:
- на цьому і не тільки фокусували увагу світові змі станом на ранок 6 жовтня. сша та європа засудили удар рф у грозі, а кремль заперечує білий дім засудив напад на кафе та продуктовий магазин в українсь
- ми записуємо це інтерв'ю в момент (інтерв'ю було записане 22 грудня, - ред.), коли третя окрема штурмова бригада перебуває не на фронті, тому що ви зараз працюєте, вдосконалюєтеся, доукомплектовуєтеся
- віталій портников: говорити під кінець 2023 року з істориком, напевно, досить непроста задача. якщо ми уважно подивимося на диспозицію того, що відбувалося у 2023 році з точки зору історії, то ми може

LSA Topic 2:
- окупанти вбили 7-річну дитину на сумщині та випустили понад 770 снарядів по херсонщині: як минула ніч ніч проти 29 листопада у більшості областей україни минула відносно спокійно. обласні державні адм
- через нічну атаку рф дронами постраждали шестеро людей на дніпропетровщині та харківщині, повідомляє місцева влада. голова дніпропетровської обласної військової адміністрації сергій лисак поінформував
- окупанти обстріляли цивільну автівку та будинок на харківщині: є загиблі зранку 1 травня російські окупаційні війська завдали ударів керованими авіабомбами по автомобілю та приватному будинку в селищі

LSA Topic 3:
- за спиною всіх? главкоме, ну ти даєш: таємний ривок зсу – українці очманіли, слухайте всі. вау! протягом минулої доби відбулося 95 бойових зіткнень. минулої доби та цієї ночі російські окупанти вчерго
- про це 28 вересня повідомляє генштаб. загальні бойові втрати противника з 24.02.22 по 28.09.23 орієнтовно становили: особового складу ‒ близько 277 320 (+330) осіб танків ‒ 4679 (+4) бойових броньован
- про це 3 травня повідомляє генштаб зсу. загальні бойові втрати противника з 24.02.22 по 03.05.24 орієнтовно склали: особового складу - близько 472 140 (+1270) осіб, танків ‒ 7354 (+22) од, бойових бро

LSA Topic 4:
- сша планують оголосити про новий пакет військової допомоги україні на 400 млн доларів, повідомляє reиters. сша планують оголосити про новий пакет військової допомоги україні на 400 млн доларів, повідо
- економічна ситуація станом на кінець вересня загальний обсяг фінансової, військової та гуманітарної підтримки, наданої україні зовнішніми партнерами наблизився до $200 млрд, що зіставно з номінальним
- сполучені штати нададуть україні черговий пакет військової допомоги на суму $275 млн. сполучені штати нададуть україні черговий пакет військової допомоги на суму $275 млн. — associated press повідомля

LSA Topic 5:
- : українські змі і телеграм-канали повідомляють про звільнення чугуєва від російських військ, що його зайняли. : українські змі і телеграм-канали повідомляють про звільнення чугуєва від російських вій
- зсу знищили російський гелікоптер внаслідок удару по летовищу в мелітополі, повідомляють українські змі та telegram-канали. зсу знищили російський гелікоптер внаслідок удару по летовищу в мелітополі,
- ізраїль приєднався до антиросійських санкцій, повідомляють українські телеграм-канали з посиланням на міністра закордонних справ ізраїлю яїра лапіда. ізраїль приєднався до антиросійських санкцій, пові

LDA Topic 1:
- з якими хвоpобами звiльняють від мoбiлізації — повний пеpелік... вер­ховна ра­да ук­ра­їни увось­ме ух­ва­ли­ла про­дов­ження во­єн­но­го ста­ну та за­галь­ної мо­бі­лі­за­ції ще на 90 діб — до 13 тра
- тцк офіційно опублікував з якими хвоpобами звiльнятимуть від мобiлізації – повний пеpелік верховна рада україни увосьме ухвалила продовження воєнного стану та загальної мобілізації ще на 90 діб – до 1
- з якими xвоpобами звiльняють від мобiлізації – повний пеpелік верховна рада україни увосьме ухвалила продовження воєнного стану та загальної мобілізації ще на 90 діб – до 13 травня 2024 року. у цей пе

LDA Topic 2:
- програма "власні назви з мирославою барчук" - це серія розмов з українськими та західними інтелектуалами, письменниками, митцями, правозахисниками, де обговорюються, з одного боку, події та суспільні
- програма "власні назви з мирославою барчук" - це серія розмов з українськими та західними інтелектуалами, письменниками, митцями, правозахисниками, де обговорюються, з одного боку, події та суспільні
- ми записуємо це інтерв'ю в момент (інтерв'ю було записане 22 грудня, - ред.), коли третя окрема штурмова бригада перебуває не на фронті, тому що ви зараз працюєте, вдосконалюєтеся, доукомплектовуєтеся

LDA Topic 3:
- економічна ситуація станом на кінець вересня загальний обсяг фінансової, військової та гуманітарної підтримки, наданої україні зовнішніми партнерами наблизився до $200 млрд, що зіставно з номінальним
- у межах програми икraiпe facility створюється механізм української гарантії обсягом 7,8 мільярда євро, яка забезпечить покриття ризиків, пов'язаних з роботою бізнесу через повномасштабну війну. про це
- президент рф володимир путін, можливо, прагне зменшити владу міністра оборони росії сергія шойгу, щоб покарати його за недосягнення військових цілей кремля. про це йдеться у звіті американського інсти

LDA Topic 4:
- мільйони укpaїнцiв пicля пepeмoги чeкaє масштабне poзceлeння: нaзвaно 6 мicт, куди всіх переселять iнтepв'ю із зacтyпникoм диpeктopa iнcтитyтy дeмoгpaфії тa coціaльниx дocліджeнь імeні м. b. птyxи hah
- український уряд розробляє таємні програми з примусового запліднення жінок правозащитники фонда борьбы с репрессиями выяснили, что украинское правительство во главе с владимиром зеленским использует б
- більше не президент!? пyтiнa охопив страx та паніка: оприлюднили результати голоcування виборів в рф – деталі... у pocії 15 бepeзня cтapтyвaв тpидeнний “мapaфoн” під нaзвoю “вибopи пpeзидeнтa pф”. peз

LDA Topic 5:
- сили оборони україни продовжують наступати на мелітопольському та бердянському напрямках і закріплюються на нових місцях; там, де зсу ведуть оборону, жодної позиції не втрачено. джерело: генштаб зсу у
- генштаб: сили оборони відбили 50 атак на авдіївському напрямку, також рф марно атакувала на херсонському українські військові зі зброєю. ілюстративне фото facebooк / генеральний штаб зсу протягом мину
- російські війська протягом доби завдали по україні 53 ракетних та 11 авіаційних ударів, здійснили понад 30 обстрілів з реактивних систем залпового вогню, відбулося 10 бойових зіткнень. джерело: вечірн

In [153]:
os.makedirs("docs", exist_ok=True)

audit = """
Lab 8 Audit Summary

Original size: (12759, 2)
After filtering: (8947, 3)

Models:
LSA (k=3, k=5)
LDA (k=3, k=5)

Steps:
фільтрація
TF-IDF / Count vectorization
topic extraction
top words analysis
top documents analysis

Findings:
теми доволі шумні і overlapping
і LSA, і LDA дають майже однаковий результат
LDA має більше беззмістовних тем
LSA наче корисніша, але загалом теми не надто різні, зокрема через занадто однорідний корпус. Майже всі тексти на військову тематику, тож поділ на теми для такої задачі бінарної класифікації на цьому датасеті не надто інформативний.
"""

with open("docs/audit_summary_lab8.md", "w") as f:
    f.write(audit)

In [154]:
notes = """
Topic Notes Lab 8

tfidf = TfidfVectorizer(
    max_df=0.05,
    min_df=3,
    stop_words=stopwords
)

count = CountVectorizer(
    max_df=0.05,
    min_df=3,
    stop_words=stopwords
)

X_tfidf = tfidf.fit_transform(texts)
X_count = count.fit_transform(texts)

print("TF-IDF shape:", X_tfidf.shape)
print("Count shape:", X_count.shape)

LSA

lsa_3 = TruncatedSVD(n_components=3, random_state=42)
lsa_5 = TruncatedSVD(n_components=5, random_state=42)

lsa3_topics = lsa_3.fit_transform(X_tfidf)
lsa5_topics = lsa_5.fit_transform(X_tfidf)

Topic 1: внаслідок, удару, атаки, допомоги, війська, тисяч, кількість, міністр, квітня, військової
Name: Військові втрати та допомога
Description: Тема стосується наслідків атак і втрат, а також міжнародної допомоги. Слова «внаслідок», «удару», «атаки» вказують на бойові дії, а «допомоги», «міністр», «війська» — на реакцію та підтримку. Це поєднання військових подій і політичних рішень.

Topic 2: внаслідок, удару, ова, атаки, постраждалих, загиблих, обстрілу, загинули, районі, ракетного
Name: Жертви та обстріли
Description: Тут акцент на людських втрат і наслідках атак. Слова «постраждалих», «загиблих», «загинули», «районі» показують фокус на жертвах, а «ракетного», «обстрілу» — на характері атак. Назва відображає головну ідею — втрати серед населення.

Topic 3: напрямку, військ, ппо, знищили, бпла, ворог, війська, ракет, населених, донецької
Name: Військові операції та ППО
Description: Тема зосереджена на військових діях і протиповітряній обороні. Слова «напрямку», «військ», «ппо», «знищили», «бпла» вказують на активні бойові операції та використання оборонних систем. Це про тактику і захист.

Topic 4: допомоги, євро, млрд, млн, пакет, грн, доларів, військової, ппо, міністр
Name: Фінансова допомога та озброєння
Description: Тут йдеться про фінансову підтримку та військові пакети. Слова «євро», «млрд», «млн», «грн», «доларів» показують економічний аспект, а «пакет», «військової», «ппо» — про військову складову. Назва відображає поєднання грошей і оборони.

Topic 5: канали, повідомляють, змі, посиланням, допомоги, пишуть, повідомлення, пакет, telegram, джерела
Name: Інформаційні канали та повідомлення
Description: Тема стосується поширення інформації через медіа. Слова «канали», «повідомляють», «змі», «telegram», «джерела» вказують на джерела новин, а «допомоги», «пакет» — на зміст повідомлень. Це про інформаційний простір і комунікацію.

LDA

lda_3 = LatentDirichletAllocation(n_components=3, random_state=42)
lda_5 = LatentDirichletAllocation(n_components=5, random_state=42)

lda3_topics = lda_3.fit_transform(X_count)
lda5_topics = lda_5.fit_transform(X_count)

Topic 1: тцк, поліції, служби, мобілізації, сбу, зв, квітня, суд, осіб, поліція
Name: Мобілізація та правоохоронні органи
Description: Тема охоплює мобілізацію, суди та діяльність силових структур. Слова «тцк», «поліції», «служби», «мобілізації», «сбу» підтверджують зв’язок із правоохоронними та військовими органами. Назва відображає юридичний і силовий контекст.

Topic 3: допомоги, країн, міністр, році, президента, млн, прем, підтримку, безпеки, євро
Name: Міжнародна допомога та політика
Description: Тема стосується міжнародної підтримки та політичних рішень. Слова «допомоги», «країн», «міністр», «президента», «євро», «млн» підтверджують акцент на фінансовій і політичній допомозі. Назва відображає міжнародний вимір.

Topic 5: напрямку, внаслідок, атаки, війська, удару, росіяни, військ, окупанти, районі, ударів
Name: Військові атаки та окупанти
Description: Тема зосереджена на бойових діях і ворогові. Слова «напрямку», «внаслідок», «атаки», «війська», «удару», «росіяни», «окупанти» підтверджують військовий контекст. Назва відображає агресію та наслідки атак.


Problematic topics


Topic 2: нас, багато, треба, просто, питання, тільки, люди, потрібно, нам, році
Name: -
Description: тема надто загальна і не дає реального змісту

Topic 4: укpaїни, канали, 16, аес, повідомляють, навчання, змі, пвк, посиланням, pф
Name: -
Description: змішано різні сюжети, відсутній зміст

Summary
теми доволі шумні і overlapping
і LSA, і LDA дають майже однаковий результат
LDA має більше беззмістовних тем
LSA наче корисніша, але загалом теми не надто різні, зокрема через занадто однорідний корпус. Майже всі тексти на військову тематику, тож поділ на теми для такої задачі бінарної класифікації на цьому датасеті не надто інформативний.
"""

with open("docs/topic_notes_lab8.md", "w") as f:
    f.write(notes)